[package]
name = "topaz-ast-to-graphviz"
version = "0.1.0"
edition = "2021"

[dependencies]
topaz-ast = {path = "../topaz-ast" }
topaz-report = {path = "../topaz-report" }
topaz-parser = {path = "../topaz-parser" }
