[package]
name = "topazc-llvm"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.topaz-ast]
path = "../../scaffold/topaz-ast"

[dependencies.topaz-parser-next]
path = "../../scaffold/topaz-parser-next"
