[package]
name = "ry-ast-to-graphviz"
version = "0.1.0"
edition = "2021"

[dependencies]
ry-ast = {path = "../topaz-ast" }
ry-report = {path = "../topaz-report" }
ry-parser = {path = "../topaz-parser" }
