[package]
name = "ry-static-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
ry-ast = {path = "../topaz-ast" }
ry-lexer = {path = "../topaz-lexer" }
ry-parser = {path = "../topaz-parser" }
ry-report = {path = "../topaz-report" }
codespan-reporting = "0.11.1"
num-traits = "0.2.15"
thiserror = "1.0.40"
