[package]
name = "sigma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = {version = "0.11.1", features = ["macros"]}
ariadne = "0.1.5"
derive_more = "0.99.17"